# Generated by Django 4.1.5 on 2024-02-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDMSapp', '0002_remove_stud_item_item_id_stud_item_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dept_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('SPORTS', 'SPORTS'), ('ATHLETICS', 'ATHLETICS')], default='Active', max_length=50),
        ),
    ]
